export enum ROUTES {
  HOME = '/',
  EDUCATIONAL_GARAGE = '/educational-garage',
  HISTORY = '/history',
  LOGIN = '/login',
  REGISTER = '/register',
  PRESENTATION_GENERATOR = '/presentation-generator',
  LESSON_PLANNER = '/lesson-planner',
  CONTEXT_BUILDER = '/context-builder',
  QUIZ_BUILDER = '/quiz-builder',
  UNIT_PLANNER = '/unit-planner',
  WORKSHEETS = '/handouts',
  STUDENT_PERFORMANCE = '/student-performance',
  PROFILE = '/profile',
  SYLLABUS_SCRIBER = '/syllabus-scriber',
}
